import {
  Project,
  TimelineEntry,
  Achievement,
  Chapter,
  EditorialPhoto,
  EducationEntry,
  IndustrialCaseStudy,
  CertificationEntry,
  EvidenceSkill,
  Essay,
} from "@/types";

export const CHAPTERS: Chapter[] = [
  {
    id: "architect",
    index: 0,
    number: "01",
    title: "THE ARCHITECT",
    subtitle: "AI & ML Engineer · Computer Vision · Enterprise AI · IoT & Embedded Systems",
    tag: "GLOBAL ENGINEERING IDENTITY",
  },
  {
    id: "artifacts",
    index: 1,
    number: "02",
    title: "THE ARTIFACTS",
    subtitle: "Production AI Systems, Computer Vision & RAG Copilots",
    tag: "PROJECT POSITIONING & ARCHITECTURE",
  },
  {
    id: "expedition",
    index: 2,
    number: "03",
    title: "THE EXPEDITION",
    subtitle: "Timeline, Evidence Skill Mesh & Verified Credentials",
    tag: "TIMELINE & CREDENTIALS",
  },
  {
    id: "journal",
    index: 3,
    number: "04",
    title: "RESEARCH & EXPLORATION",
    subtitle: "Ideas, experiments, engineering decisions, and technical investigations behind the AI systems I build.",
    tag: "RESEARCH & EXPLORATION",
  },
  {
    id: "transmission",
    index: 4,
    number: "05",
    title: "TRANSMISSION",
    subtitle: "Future Vision & Direct Contact",
    tag: "CONNECT & LEADERSHIP",
  },
];

export const EDITORIAL_PHOTOS: EditorialPhoto[] = [
  {
    src: "/assets/me.jpg",
    alt: "Swarnava Sarkar — AI & ML Engineer",
    caption: "Swarnava Sarkar • SRM Institute of Science & Technology",
    aspectRatio: "portrait",
  },
  {
    src: "/assets/me1.png",
    alt: "Swarnava Sarkar — Editorial Portrait",
    caption: "Swarnava Sarkar • First-Principles Engineering",
    aspectRatio: "square",
  },
];

export const ENGINEERING_TITLES = [
  "AI & ML Engineer",
  "Computer Vision Engineer",
  "Enterprise AI Engineer",
  "IoT & Embedded Systems Engineer",
  "Software Engineer",
  "Full Stack Developer",
  "Research Engineer",
  "Industrial AI Developer",
  "Apple Student Developer",
];

export const ENGINEERING_DOMAINS = [
  "Artificial Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Computer Vision",
  "Generative AI",
  "Large Language Models",
  "Retrieval-Augmented Generation (RAG)",
  "Industrial AI",
  "High Performance Computing (HPC)",
  "Geophysical Computing",
  "Seismic AI",
  "Backend Engineering",
  "Full Stack Development",
  "API Engineering",
  "Distributed Systems",
  "IoT",
  "Embedded Systems",
  "Edge AI",
  "Environmental AI",
  "Automation",
  "Research Engineering",
];

export const CURRENT_INTERESTS = [
  "Enterprise AI",
  "Industrial AI",
  "Computer Vision",
  "RAG Systems",
  "LLMs",
  "Developer Copilots",
  "High Performance Computing",
  "IoT",
  "Embedded AI",
  "Edge Intelligence",
  "Scientific Computing",
];

export const RESEARCH_INTERESTS = [
  "Computer Vision",
  "Industrial AI",
  "Generative AI",
  "Geophysical AI",
  "Edge AI",
  "Embedded Intelligence",
  "Environmental AI",
  "Human-Centered AI",
];

export const IDENTITY_DATA = {
  name: "SWARNAVA SARKAR",
  role: "AI & ML Engineer · Computer Vision Engineer · Enterprise AI Engineer",
  subtitle: "AI & ML Engineer · Computer Vision Engineer · Enterprise AI Engineer · IoT & Embedded Systems Engineer · Software Engineer · Full Stack Developer · Research Engineer · Industrial AI Developer · Apple Student Developer",
  university: "SRM Institute of Science and Technology",
  degree: "B.Tech Computer Science Engineering (AI & ML Specialization)",
  location: "Chennai, Tamil Nadu, India",
  currentlyBuilding: "HPCC Copilot, SeisVision AI, Enterprise AI Systems",
  currentlyBuildingList: ["HPCC Copilot", "SeisVision AI", "Enterprise AI Systems"],
  researching: "Computer Vision & Seismic Signal Processing",
  learning: "Apple iOS Development & Swift Architecture",
  mission: "Build AI systems that solve real industrial problems.",
  status: "Active Engineering & AI Research",
  email: "swarnava2019@gmail.com",
  github: "https://github.com/SWARNAVA182006",
  linkedin: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  affiliations: [
    {
      name: "Apple Student Developer",
      logoSrc: "/assets/ios.jpg",
      details: "Selected for prestigious Apple iOS Student Developer Program, building native Swift/SwiftUI apps & CoreML inference.",
    },
    {
      name: "ONGC",
      logoSrc: "/assets/ongc.png",
      details: "AI & ML Intern at Oil and Natural Gas Corporation, processing subsurface seismic SEG-Y datasets & fault models.",
    },
    {
      name: "SRMIST",
      logoSrc: "/assets/srm.png",
      details: "B.Tech Computer Science Engineering (AI & ML Specialization) at SRM Institute of Science and Technology, Kattankulathur.",
    },
  ],
};

export const EDUCATION_DATA: EducationEntry = {
  institution: "SRM Institute of Science and Technology, Kattankulathur",
  degree: "Bachelor of Technology (B.Tech)",
  specialization: "Computer Science Engineering (AI & ML Specialization)",
  period: "2022 — 2026",
  location: "Chennai, Tamil Nadu, India",
  currentCgpa: "B.Tech CSE (AI & ML)",
  relevantCoursework: [
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Data Structures & Algorithms (DSA)",
    "Operating Systems",
    "Computer Networks",
    "Database Management Systems (DBMS)",
  ],
  researchHighlights: [
    "Undergraduate Research Opportunity Program (UROP) Scholar under Dr. Vidhya B of SRM, Assistant Professor",
    "Seismic Processing Computer Vision Pipeline Development",
    "Guidewire DevTrails National Finalist",
  ],
  academicAchievements: [
    "Apple Student Developer Program Selection",
    "ONGC AI & ML Internship Selection",
    "Google AICTE Virtual Internship Selection",
  ],
};

// Exact timeline sequence: SRMIST -> UROP -> Google AICTE -> IBM -> OpenAI -> StudAI -> ONGC -> Guidewire DevTrails Finalist -> TechForce Academy Australia -> Apple Student Developer Program Selection
export const TIMELINE_EVENTS: TimelineEntry[] = [
  {
    period: "2022",
    title: "Entered SRMIST (B.Tech CSE AI & ML)",
    organization: "SRM Institute of Science and Technology",
    type: "Education",
    location: "Chennai, India",
    description: "Entered SRMIST to specialize in AI & Machine Learning, building core CS foundations in DSA, OOP, and linear algebra.",
    highlights: ["First-principles computer science focus", "Explored Python, C++, and Neural Network algorithms"],
    skillsUsed: ["Python", "C++", "Java", "Data Structures", "Linear Algebra"],
    logoSrc: "/assets/srm.png",
  },
  {
    period: "2023 — 2024",
    title: "Undergraduate Research Scholar (UROP) — Under Dr. Vidhya B",
    organization: "SRM Institute of Science and Technology (Under Dr. Vidhya B, Asst. Professor)",
    type: "Research",
    location: "Chennai, India",
    description: "Selected for UROP research scholar role under Dr. Vidhya B of SRM, Assistant Professor, exploring computer vision and signal processing.",
    highlights: ["Mentored by Dr. Vidhya B, Assistant Professor at SRM", "Computer Vision & Signal Processing research"],
    skillsUsed: ["PyTorch", "OpenCV", "Python", "NumPy", "Computer Vision"],
    logoSrc: "/assets/urop.jpg",
  },
  {
    period: "2024",
    title: "Google AICTE Virtual Internship",
    organization: "Google for Developers & EduSkills & AICTE",
    type: "Internship",
    location: "Virtual",
    description: "Completed intensive AI/ML virtual internship program focused on TensorFlow, Cloud AI, and modern ML pipelines.",
    highlights: ["Google Developer AI certificate", "Enterprise ML workflow training"],
    skillsUsed: ["TensorFlow", "Google Cloud", "Python", "Machine Learning"],
    logoSrc: "/assets/google.png",
  },
  {
    period: "2024",
    title: "IBM Machine Learning Specialization",
    organization: "IBM",
    type: "Program",
    location: "Virtual",
    description: "Earned IBM professional certification covering supervised learning, deep learning, and model optimization.",
    highlights: ["IBM verified ML credential", "Model validation & hyperparameter tuning"],
    skillsUsed: ["Python", "Scikit-learn", "Deep Learning", "IBM Watson"],
    logoSrc: "/assets/ibm.jpg",
  },
  {
    period: "2024",
    title: "OpenAI Developer Workshop",
    organization: "OpenAI",
    type: "Program",
    location: "Virtual",
    description: "Participated in OpenAI developer sessions focused on prompt engineering, embeddings, and API integration.",
    highlights: ["GPT-4 API integration", "Embedding vector search implementation"],
    skillsUsed: ["OpenAI API", "LangChain", "Qdrant", "Generative AI"],
    logoSrc: "/assets/openai.jpg",
  },
  {
    period: "2024",
    title: "AIML Engineer Intern — StudAI One",
    organization: "StudAI One",
    type: "Internship",
    location: "Remote / India",
    description: "Engineered AI backend services, intelligent query engines, and educational copilot workflows.",
    highlights: ["Developed production FastAPI endpoints", "RAG vector retrieval tuning"],
    skillsUsed: ["FastAPI", "Python", "Retrieval-Augmented Generation (RAG)", "Qdrant"],
    logoSrc: "/assets/studai.jpg",
  },
  {
    period: "2024",
    title: "AI & ML Intern — ONGC",
    organization: "Oil and Natural Gas Corporation (ONGC)",
    type: "Internship",
    location: "India",
    description: "AI & ML summer internship analyzing geophysical seismic datasets and building computational ML pipelines.",
    highlights: ["Subsurface seismic data processing", "Geophysical AI interpretation"],
    skillsUsed: ["Geophysical Computing", "Seismic AI", "SEG-Y", "Python", "PyTorch"],
    logoSrc: "/assets/ongc.png",
  },
  {
    period: "2024",
    title: "Guidewire DevTrails Finalist",
    organization: "Guidewire",
    type: "Competition",
    location: "India",
    description: "Selected as national finalist in Guidewire DevTrails competition for architecting ClaimsAssist AI policyholder copilot.",
    highlights: ["National finalist placement", "Enterprise insurance AI architecture"],
    skillsUsed: ["TypeScript", "React", "FastAPI", "Insurance Technology"],
    logoSrc: "/assets/guidewire.jpg",
  },
  {
    period: "2024",
    title: "Software Engineering Project Intern — TechForce Academy Australia",
    organization: "TechForce Academy Australia",
    type: "Internship",
    location: "Remote / Australia",
    description: "Engineered PerformPro — an employee performance management and analytics dashboard platform for TechForce Academy Australia.",
    highlights: ["Built FastAPI analytics backend", "Designed React metrics dashboard"],
    skillsUsed: ["FastAPI", "React", "PostgreSQL", "Backend Engineering"],
    logoSrc: "/assets/techforce.webp",
  },
  {
    period: "2025",
    title: "Apple Student Developer Program Selection",
    organization: "Apple Developer Program",
    type: "Program",
    location: "Chennai / Cupertino",
    description: "Selected for prestigious Apple iOS Student Developer Program, building native Swift/SwiftUI applications.",
    highlights: ["Apple program selection", "Native iOS & Swift architecture"],
    skillsUsed: ["Swift", "iOS", "Embedded Systems", "Edge AI"],
    logoSrc: "/assets/ios.jpg",
  },
];

export const INDUSTRIAL_CASE_STUDIES: IndustrialCaseStudy[] = [
  {
    id: "ongc",
    company: "Oil and Natural Gas Corporation (ONGC)",
    role: "AI & ML Intern",
    period: "Summer 2024",
    location: "India",
    objective: "Analyze subsurface seismic dataset anomalies and evaluate machine learning models for geological fault identification.",
    whatIWorkedOn: [
      "Processed multi-gigabyte seismic SEG-Y datasets using custom Python signal pipelines.",
      "Trained 2D/3D convolutional architectures for automated horizon and fault line extraction.",
      "Delivered technical evaluation report to ONGC domain geophysicists.",
    ],
    technologies: ["Python", "PyTorch", "OpenCV", "NumPy", "SEG-Y"],
    challenges: ["High noise ratio in raw seismic data requiring custom filtering.", "Large 3D volume memory constraints on standard GPUs."],
    learnings: ["First-principles domain alignment is critical before applying ML models.", "Handling enterprise industrial data pipelines requires strict validation."],
    outcome: "Successfully demonstrated automated fault detection workflow with high boundary precision.",
    logoSrc: "/assets/ongc.png",
  },
  {
    id: "studai",
    company: "StudAI One",
    role: "AIML Engineer Intern",
    period: "2024",
    location: "Remote / India",
    objective: "Architect high-performance AI query backend services and RAG knowledge retrieval systems.",
    whatIWorkedOn: [
      "Built asynchronous FastAPI microservices serving LLM retrieval pipelines.",
      "Optimized vector search indexing and chunking strategies to minimize hallucinations.",
    ],
    technologies: ["FastAPI", "Python", "LangChain", "Qdrant", "Docker"],
    challenges: ["Minimizing response latency for multi-turn user conversations."],
    learnings: ["Designing deterministic guardrails around probabilistic LLM APIs is mandatory."],
    outcome: "Deployed stable backend microservices powering intelligent student copilot interfaces.",
    logoSrc: "/assets/studai.jpg",
  },
  {
    id: "apple",
    company: "Apple Developer Program",
    role: "Apple Student Developer",
    period: "2025",
    location: "Chennai / Cupertino",
    objective: "Master native iOS engineering principles, Swift programming, and on-device inference.",
    whatIWorkedOn: [
      "Engineered native SwiftUI applications utilizing modern state management.",
      "Integrated model runtimes for local on-device inference.",
    ],
    technologies: ["Swift", "TypeScript", "Edge AI", "iOS"],
    challenges: ["Optimizing memory allocation for local neural network inference."],
    learnings: ["Platform-native design language creates unparalleled user delight."],
    outcome: "Earned selection into Apple's premier student developer initiative.",
    logoSrc: "/assets/ios.jpg",
  },
  {
    id: "techforce",
    company: "TechForce Academy Australia",
    role: "Software Engineering Project Intern",
    period: "2024",
    location: "Remote / Australia",
    objective: "Develop PerformPro employee performance management dashboard with FastAPI and PostgreSQL.",
    whatIWorkedOn: [
      "Built REST microservices for employee metrics tracking and authorization.",
      "Integrated React dashboard visualization for real-time analytics.",
    ],
    technologies: ["FastAPI", "React", "PostgreSQL", "TypeScript", "REST APIs"],
    challenges: ["Securing sensitive employee metrics with strict role validation."],
    learnings: ["Clean REST API architecture simplifies frontend state management."],
    outcome: "Delivered production PerformPro platform for TechForce Academy Australia.",
    logoSrc: "/assets/techforce.webp",
  },
];

export const PROJECTS: Project[] = [
  {
    id: "seisvision",
    title: "SeisVision AI",
    subtitle: "Enterprise AI · Computer Vision · Geophysical Computing · Seismic Interpretation",
    tagline: "Computer vision segmentation engine for industrial geophysical interpretation.",
    category: "Enterprise AI · Computer Vision · Geophysical Computing",
    featured: true,
    year: "2024",
    impactMetrics: [
      { label: "Domain", value: "Geophysical Computing" },
      { label: "Pipeline", value: "SEG-Y Signal Processing" },
      { label: "Stack", value: "PyTorch & OpenCV & FastAPI" },
    ],
    description: "AI-assisted seismic interpretation software utilizing custom computer vision pipelines to process 2D profiles and 3D SEG-Y volumes for automated geological fault line extraction.",
    techStack: ["Enterprise AI", "Computer Vision", "Geophysical Computing", "Seismic Interpretation", "Deep Learning", "FastAPI", "Docker", "SEG-Y", "PyTorch", "Python", "OpenCV"],
    githubUrl: "https://github.com/SWARNAVA182006/SeisVisionAI.git",
    caseStudy: {
      problemStatement: "Manual seismic fault interpretation requires hundreds of expert hours per survey.",
      motivation: "Automating geological fault segmentation accelerates subsurface reservoir characterization.",
      research: "Applied computer vision segmentation backbones trained on seismic amplitude slices.",
      systemArchitecture: [
        "SEG-Y Reader & Signal Preprocessing Filter",
        "Computer Vision Segmentation Engine (PyTorch)",
        "FastAPI REST API & Slice Visualization Canvas",
      ],
      developmentProcess: ["Preprocessed raw amplitude arrays using z-score normalization and AGC filtering."],
      challengesAndSolutions: [{ challenge: "High noise in raw acoustic seismic reflection data.", solution: "Applied contrast-limited adaptive histogram equalization and AGC filtering." }],
      impact: ["Automated fault line mapping from 2D profiles and 3D SEG-Y volumes."],
      lessonsLearned: ["Domain-specific preprocessing contributes significantly to segmentation clarity."],
    },
  },
  {
    id: "hpcc-copilot",
    title: "HPCC Copilot",
    subtitle: "Enterprise AI · Generative AI · LLMs · RAG · High Performance Computing",
    tagline: "Domain-tailored AI developer assistant for parallel HPC software development.",
    category: "Enterprise AI · Generative AI · RAG · HPC",
    featured: true,
    year: "2024",
    impactMetrics: [
      { label: "Domain", value: "High Performance Computing" },
      { label: "Architecture", value: "Retrieval-Augmented Generation" },
      { label: "Parser Core", value: "Treesitter AST Validation" },
    ],
    description: "Enterprise offline AI Copilot providing developer assistance, knowledge retrieval, and real-time Abstract Syntax Tree (AST) validation for HPC parallel C/C++ and CUDA programming.",
    techStack: ["Enterprise AI", "Generative AI", "LLMs", "Retrieval-Augmented Generation (RAG)", "High Performance Computing (HPC)", "Developer Copilot", "AST Validation", "FastAPI", "Python", "TypeScript", "LangChain", "Qdrant", "Docker"],
    githubUrl: "https://github.com/SWARNAVA182006/HPCC-Copilot.git",
    caseStudy: {
      problemStatement: "Generic LLMs produce invalid MPI and OpenMP parallel pragmas due to lack of HPC syntax verification.",
      motivation: "HPC development requires deterministic correctness backed by static AST parsers.",
      research: "Integrated Treesitter AST parsing with parallel C/C++ static syntax checkers.",
      systemArchitecture: ["Offline Developer Prompt Receiver", "LLM RAG Retrieval Core", "Treesitter AST Validator", "WebSocket Gateway"],
      developmentProcess: ["Indexed parallel programming documentation into local vector store."],
      challengesAndSolutions: [{ challenge: "Preventing syntax hallucinations in parallel directives.", solution: "Created post-generation AST inspector that verifies C/CUDA pragmas." }],
      impact: ["Delivered offline developer assistance with AST static syntax verification."],
      lessonsLearned: ["Coupling LLM generation with deterministic AST static checkers eliminates syntax errors."],
    },
  },
  {
    id: "forestnet",
    title: "ForestNet AI",
    subtitle: "AI · IoT · Embedded Systems · Environmental AI · Edge AI",
    tagline: "Multispectral remote sensing and IoT hardware monitoring for forest reserves.",
    category: "AI · IoT · Embedded Systems · Edge AI",
    featured: true,
    year: "2024",
    impactMetrics: [
      { label: "Domain", value: "Environmental AI & IoT" },
      { label: "Hardware", value: "ESP32 & LoRa Gateway" },
      { label: "Imagery", value: "Satellite Multispectral NDVI" },
    ],
    description: "Environmental AI platform combining satellite multispectral remote sensing with ESP32 LoRa IoT sensor nodes for real-time deforestation monitoring and anomaly detection.",
    techStack: ["AI", "IoT", "Embedded Systems", "Environmental AI", "Edge AI", "ESP32", "LoRa", "Satellite Monitoring", "Real-time Monitoring", "Python", "PyTorch", "OpenCV", "GPS"],
    githubUrl: "https://github.com/SWARNAVA182006/Eco-ranger2.git",
    caseStudy: {
      problemStatement: "Manual forest monitoring cannot scale across wide geographical reserves.",
      motivation: "Combining satellite NDVI imagery with IoT ground sensors provides instant anomaly alerts.",
      research: "Utilized Normalized Difference Vegetation Index (NDVI) temporal change maps.",
      systemArchitecture: ["Satellite Imagery Ingestion Engine", "NDVI Band Computation Core", "ESP32 LoRa IoT Sensor Mesh", "Alert Dashboard"],
      developmentProcess: ["Engineered custom Rasterio loader for 10m multispectral GeoTIFF files."],
      challengesAndSolutions: [{ challenge: "Cloud cover distortion in optical satellite bands.", solution: "Applied temporal median compositing across consecutive satellite passes." }],
      impact: ["Enabled automated canopy loss tracking and environmental anomaly alerts."],
      lessonsLearned: ["Combining satellite imagery with ground IoT sensors creates robust monitoring systems."],
    },
  },
  {
    id: "performpro",
    title: "PerformPro AI",
    subtitle: "Full Stack Engineering · FastAPI · PostgreSQL · Backend Systems",
    tagline: "Developed for TechForce Academy Australia.",
    category: "Full Stack Engineering · Backend Systems",
    featured: false,
    year: "2024",
    impactMetrics: [
      { label: "Organization", value: "TechForce Academy Australia" },
      { label: "Architecture", value: "FastAPI & PostgreSQL" },
      { label: "Security", value: "REST APIs & JWT" },
    ],
    description: "Employee performance management and analytics dashboard platform built for TechForce Academy Australia, featuring FastAPI microservices, PostgreSQL, React, and JWT authentication.",
    techStack: ["Full Stack Engineering", "FastAPI", "PostgreSQL", "Backend Engineering", "Authentication", "REST APIs", "Analytics", "TypeScript", "React", "Python", "Docker"],
    githubUrl: "https://github.com/SWARNAVA182006/PerformPro.git",
    caseStudy: {
      problemStatement: "Organizations need structured employee metrics dashboards with secure authentication.",
      motivation: "Building an enterprise performance portal for TechForce Academy Australia.",
      research: "Designed role-based access control and analytics aggregation formulas.",
      systemArchitecture: ["React Analytics UI", "FastAPI REST Microservices", "PostgreSQL Relational DB", "JWT Auth Manager"],
      developmentProcess: ["Developed secure JWT token authorization and metrics calculation endpoints."],
      challengesAndSolutions: [{ challenge: "Securing role-based endpoints.", solution: "Implemented OAuth2 password flow with JWT bearer tokens." }],
      impact: ["Delivered production employee performance management platform for TechForce Academy Australia."],
      lessonsLearned: ["Modular REST microservices streamline multi-role enterprise web apps."],
    },
  },
  {
    id: "claimsassist-ai",
    title: "ClaimsAssist AI — Guidewire DevTrails Finalist Project",
    subtitle: "Software Engineering · Enterprise Development · Guidewire · Insurance Technology",
    tagline: "National Finalist Project for Guidewire DevTrails Competition.",
    category: "Software Engineering · Insurance Technology",
    featured: false,
    year: "2024",
    impactMetrics: [
      { label: "Honors", value: "Guidewire DevTrails Finalist" },
      { label: "Domain", value: "Insurance Technology" },
      { label: "Stack", value: "React & FastAPI" },
    ],
    description: "Insurance domain claims intake and policyholder assistance platform engineered for the Guidewire DevTrails competition, placing as a National Finalist.",
    techStack: ["Software Engineering", "Enterprise Development", "Guidewire", "Insurance Technology", "Full Stack Development", "React", "FastAPI", "TypeScript", "Python"],
    githubUrl: "https://github.com/SWARNAVA182006",
    caseStudy: {
      problemStatement: "Insurance claims intake requires manual document inspection and damage verification.",
      motivation: "Automating insurance claims processing with vision damage inspection and policy AI.",
      research: "Integrated vision APIs for damage classification with Guidewire insurance schema rules.",
      systemArchitecture: ["Claim Intake Form React UI", "Vision Damage Assessment API", "Policy Query RAG Agent"],
      developmentProcess: ["Developed damage photo upload and locator."],
      challengesAndSolutions: [{ challenge: "Formatting non-deterministic AI outputs.", solution: "Used Pydantic JSON schema enforcing on LLM responses." }],
      impact: ["Selected as National Finalist in Guidewire DevTrails competition."],
      lessonsLearned: ["Enforcing strict Pydantic schemas on LLM outputs guarantees enterprise compatibility."],
    },
  },
  {
    id: "smart-irrigation",
    title: "Smart Irrigation System",
    subtitle: "IoT · ESP32 · Sensors · Automation · Embedded Systems · Smart Agriculture",
    tagline: "Precision soil moisture monitoring & automated water conservation.",
    category: "IoT · Embedded Systems · Automation",
    featured: false,
    year: "2023",
    impactMetrics: [
      { label: "Domain", value: "IoT & Embedded Systems" },
      { label: "Hardware", value: "ESP32 & Sensors" },
      { label: "Target", value: "Smart Agriculture Automation" },
    ],
    description: "Precision soil moisture monitoring and automated water conservation system utilizing ESP32 microcontroller nodes and environmental sensors.",
    techStack: ["IoT", "ESP32", "ESP8266", "Arduino Uno", "Sensors", "Automation", "Embedded Systems", "Smart Agriculture", "Python", "C++"],
    githubUrl: "https://github.com/SWARNAVA182006",
    caseStudy: {
      problemStatement: "Agricultural water waste due to manual unmetered irrigation.",
      motivation: "Building automated sensor-driven irrigation nodes.",
      research: "Trained soil moisture regression model.",
      systemArchitecture: ["ESP32 Node", "MQTT Broker", "Flask Portal"],
      developmentProcess: ["Deployed hardware sensors."],
      challengesAndSolutions: [{ challenge: "Network drops.", solution: "Implemented local queue buffer." }],
      impact: ["Demonstrated automated soil moisture irrigation control."],
      lessonsLearned: ["Hardware IoT systems require fallback logic."],
    },
  },
  {
    id: "autism-detection",
    title: "Autism Detection AI",
    subtitle: "Machine Learning · Healthcare AI · Classification · Predictive Analytics",
    tagline: "Computer vision screening framework using facial landmark tracking.",
    category: "Machine Learning · Healthcare AI",
    featured: false,
    year: "2023",
    impactMetrics: [
      { label: "Domain", value: "Healthcare AI" },
      { label: "Method", value: "Computer Vision Classification" },
      { label: "Core Tech", value: "OpenCV & PyTorch" },
    ],
    description: "Computer vision preliminary screening framework using facial landmark tracking and eye-gaze pattern classification.",
    techStack: ["Machine Learning", "Healthcare AI", "Classification", "Predictive Analytics", "OpenCV", "PyTorch", "Python", "Scikit-learn"],
    githubUrl: "https://github.com/SWARNAVA182006",
    caseStudy: {
      problemStatement: "Early autism screening is often delayed due to clinical specialist access.",
      motivation: "Providing preliminary vision screening support.",
      research: "Analyzed eye-gaze tracking heatmaps.",
      systemArchitecture: ["Video Capture", "Landmark Extractor", "PyTorch Classifier"],
      developmentProcess: ["Extracted 68 facial landmarks."],
      challengesAndSolutions: [{ challenge: "Lighting variations.", solution: "Applied CLAHE histogram equalization." }],
      impact: ["Demonstrated video-based screening feasibility."],
      lessonsLearned: ["Preprocessing lighting normalization is crucial."],
    },
  },
];

export const RESEARCH_DATA = {
  overview: "Ideas, experiments, engineering decisions, and technical investigations behind the AI systems I build.",
  areas: [
    {
      title: "Researching Seismic Computer Vision",
      focus: "Exploration of seismic AI pipelines, SEG-Y processing, AGC filtering, U-Net and Vision Transformer architectures, fault and horizon interpretation, and industrial visualization techniques developed during the ONGC internship.",
      technologies: ["PyTorch", "CUDA", "SEG-Y Processing", "OpenCV", "Computer Vision", "Geophysical Computing"],
      status: "Exploration & ONGC Internship Research",
    },
    {
      title: "Building Enterprise AI Copilots",
      focus: "Research into offline RAG architectures, AST validation, enterprise knowledge retrieval, developer copilots, reasoning workflows, and secure AI systems inspired by the HPCC Copilot project.",
      technologies: ["Treesitter AST", "FastAPI", "Python", "Retrieval-Augmented Generation (RAG)", "Generative AI", "LLMs"],
      status: "Exploration & HPCC Systems Research",
    },
  ],
  notes: [
    {
      title: "First-Principles Engineering",
      summary: "Probabilistic AI models must be anchored by deterministic validation rules and domain-specific preprocessing.",
    },
  ],
};

export const ACHIEVEMENTS_DATA: Achievement[] = [
  {
    title: "Apple Student Developer Program Selection",
    organization: "Apple Developer Program",
    year: "2025",
    description: "Selected into prestigious Apple initiative for native Swift and iOS development.",
    badge: "Apple Student Developer",
    logoSrc: "/assets/ios.jpg",
  },
  {
    title: "AI & ML Intern — ONGC",
    organization: "Oil and Natural Gas Corporation (ONGC)",
    year: "2024",
    description: "Earned industrial research internship analyzing subsurface seismic datasets.",
    badge: "ONGC AI Engineering Intern",
    logoSrc: "/assets/ongc.png",
  },
  {
    title: "Guidewire DevTrails Finalist",
    organization: "Guidewire",
    year: "2024",
    description: "Selected as national finalist for architecting ClaimsAssist AI policyholder copilot.",
    badge: "Guidewire DevTrails Finalist",
    logoSrc: "/assets/guidewire.jpg",
  },
  {
    title: "Google AICTE Virtual Internship Selection",
    organization: "Google for Developers & EduSkills & AICTE",
    year: "2024",
    description: "Completed intensive AI/ML virtual internship program covering TensorFlow and Cloud AI.",
    badge: "Google for Developers AICTE",
    logoSrc: "/assets/google.png",
  },
  {
    title: "IBM Machine Learning Specialization",
    organization: "IBM",
    year: "2024",
    description: "Earned professional IBM certification in Machine Learning and Deep Learning architectures.",
    badge: "IBM Machine Learning",
    logoSrc: "/assets/ibm.jpg",
  },
  {
    title: "OpenAI Developer Workshop Participant",
    organization: "OpenAI",
    year: "2024",
    description: "Participated in OpenAI technical workshop covering advanced prompt engineering and vector embeddings.",
    badge: "OpenAI Generative AI",
    logoSrc: "/assets/openai.jpg",
  },
  {
    title: "Undergraduate Research Opportunity Program (UROP) Scholar — Under Dr. Vidhya B",
    organization: "SRM Institute of Science and Technology (Under Dr. Vidhya B, Asst. Professor)",
    year: "2023 — 2024",
    description: "Selected for undergraduate research program under Dr. Vidhya B of SRM, Assistant Professor, in computer vision and deep learning.",
    badge: "Research Scholar",
    logoSrc: "/assets/urop.jpg",
  },
];

export const EVIDENCE_SKILLS: EvidenceSkill[] = [
  {
    name: "Python",
    category: "AI & Machine Learning",
    tag: "Core Language",
    projectsUsed: [
      { title: "SeisVision AI", id: "seisvision" },
      { title: "HPCC Copilot", id: "hpcc-copilot" },
      { title: "PerformPro AI", id: "performpro" },
      { title: "ForestNet AI", id: "forestnet" },
    ],
    internshipsUsed: ["ONGC (AI & ML Intern)", "StudAI One", "UROP Research (Dr. Vidhya B)", "Google AICTE"],
    yearsUsed: "3+ Years",
    evidenceSummary: "Primary language used across seismic pipelines, FastAPI microservices, and neural networks.",
  },
  {
    name: "PyTorch & TensorFlow",
    category: "AI & Machine Learning",
    tag: "Deep Learning",
    projectsUsed: [
      { title: "SeisVision AI", id: "seisvision" },
      { title: "ForestNet AI", id: "forestnet" },
      { title: "Autism Detection AI", id: "autism-detection" },
    ],
    internshipsUsed: ["ONGC", "UROP Research", "Google AICTE"],
    yearsUsed: "2+ Years",
    evidenceSummary: "Custom vision models, loss functions, and CUDA GPU acceleration.",
  },
  {
    name: "OpenCV",
    category: "AI & Machine Learning",
    tag: "Computer Vision",
    projectsUsed: [
      { title: "SeisVision AI", id: "seisvision" },
      { title: "ForestNet AI", id: "forestnet" },
      { title: "Autism Detection AI", id: "autism-detection" },
    ],
    internshipsUsed: ["ONGC", "UROP Research"],
    yearsUsed: "2+ Years",
    evidenceSummary: "Seismic array filtering, image matrix manipulation, and landmark extraction.",
  },
  {
    name: "FastAPI & REST APIs",
    category: "Backend & Systems Architecture",
    tag: "REST & Microservices",
    projectsUsed: [
      { title: "HPCC Copilot", id: "hpcc-copilot" },
      { title: "PerformPro AI (TechForce Academy Australia)", id: "performpro" },
      { title: "ClaimsAssist AI", id: "claimsassist-ai" },
    ],
    internshipsUsed: ["StudAI One", "TechForce Academy Australia"],
    yearsUsed: "2+ Years",
    evidenceSummary: "Asynchronous REST microservices, Pydantic schema validation, and streaming SSE.",
  },
  {
    name: "React & Next.js & TypeScript",
    category: "Frontend & User Experience",
    tag: "Modern Web",
    projectsUsed: [
      { title: "HPCC Copilot", id: "hpcc-copilot" },
      { title: "PerformPro AI (TechForce Academy Australia)", id: "performpro" },
      { title: "ClaimsAssist AI", id: "claimsassist-ai" },
    ],
    internshipsUsed: ["StudAI One", "TechForce Academy Australia"],
    yearsUsed: "2+ Years",
    evidenceSummary: "Building high-performance interactive web applications and Framer Motion visual systems.",
  },
  {
    name: "Swift & C++ & Java",
    category: "Systems & Embedded",
    tag: "Native Languages",
    projectsUsed: [
      { title: "Smart Irrigation System", id: "smart-irrigation" },
    ],
    internshipsUsed: ["Apple Developer Program", "SRMIST"],
    yearsUsed: "2 Years",
    evidenceSummary: "Native Apple iOS development, CoreML model integration, C++ hardware microcontrollers, and Java programming.",
  },
  {
    name: "ESP32 & LoRa & Embedded Systems",
    category: "IoT & Embedded Systems",
    tag: "Hardware & Edge",
    projectsUsed: [
      { title: "ForestNet AI", id: "forestnet" },
      { title: "Smart Irrigation System", id: "smart-irrigation" },
    ],
    internshipsUsed: ["UROP Research"],
    yearsUsed: "2 Years",
    evidenceSummary: "ESP32 microcontroller nodes, LoRa gateways, sensor telemetry, and Edge AI deployment.",
  },
  {
    name: "PostgreSQL & Docker & Qdrant",
    category: "Backend & Systems Architecture",
    tag: "Databases & DevOps",
    projectsUsed: [
      { title: "PerformPro AI (TechForce Academy Australia)", id: "performpro" },
      { title: "HPCC Copilot", id: "hpcc-copilot" },
    ],
    internshipsUsed: ["StudAI One", "TechForce Academy Australia"],
    yearsUsed: "2+ Years",
    evidenceSummary: "Relational database schema architecture, containerization, and vector retrieval search.",
  },
];

export const CERTIFICATIONS_DATA: CertificationEntry[] = [
  {
    id: "apple-cert",
    title: "Apple Student Developer Program Selection",
    issuer: "Apple Developer Program",
    date: "2025",
    description: "Selected into Apple's program for native iOS engineering and SwiftUI design.",
    logoSrc: "/assets/ios.jpg",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "google-cert",
    title: "Google for Developers AICTE Virtual Internship Certificate",
    issuer: "Google for Developers & EduSkills & AICTE",
    date: "2024",
    description: "Verified certificate in TensorFlow, Cloud AI, and ML deployment.",
    logoSrc: "/assets/google.png",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "ibm-cert",
    title: "IBM Machine Learning Specialization",
    issuer: "IBM",
    date: "2024",
    description: "Professional certification covering supervised learning and deep neural networks.",
    logoSrc: "/assets/ibm.jpg",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "openai-cert",
    title: "OpenAI Generative AI Workshop Certificate",
    issuer: "OpenAI",
    date: "2024",
    description: "Completed technical workshop in GPT-4 API integration and vector embeddings.",
    logoSrc: "/assets/openai.jpg",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "infosys-cert",
    title: "Infosys Generative AI Certification",
    issuer: "Infosys",
    date: "2024",
    description: "Verified credential in Generative AI architectures and enterprise LLM deployment.",
    logoSrc: "/assets/infosys.jpg",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "nptel-cert",
    title: "NPTEL National Certification",
    issuer: "NPTEL",
    date: "2023",
    description: "National academic certification in computer science foundational domains.",
    logoSrc: "/assets/nptel.jpg",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "eduskills-cert",
    title: "EduSkills AI/ML Certificate",
    issuer: "EduSkills",
    date: "2024",
    description: "Verified technical certificate in cloud AI deployment.",
    logoSrc: "/assets/eduskills.png",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "ongc-cert",
    title: "AI & ML Internship Certificate",
    issuer: "Oil and Natural Gas Corporation (ONGC)",
    date: "2024",
    description: "Completed industrial internship analyzing seismic geophysical datasets.",
    logoSrc: "/assets/ongc.png",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
  {
    id: "urop-cert",
    title: "UROP Research Scholar Certificate — Under Dr. Vidhya B",
    issuer: "SRM Institute of Science and Technology",
    date: "2024",
    description: "Research completion certificate in computer vision under Dr. Vidhya B, Assistant Professor.",
    logoSrc: "/assets/urop.jpg",
    verificationUrl: "https://www.linkedin.com/in/swarnava-sarkar-8a3904336/",
  },
];

export const ESSAYS: Essay[] = [
  {
    id: "seismic-vision-research",
    slug: "seismic-vision-research",
    title: "Researching Seismic Computer Vision",
    date: "2024",
    readTime: "Exploration Topic",
    category: "Computer Vision • Geophysics",
    summary: "Exploration of seismic AI pipelines, SEG-Y processing, AGC filtering, U-Net and Vision Transformer architectures, fault and horizon interpretation, and industrial visualization techniques developed during the ONGC internship.",
    content: "Exploration of seismic AI pipelines, SEG-Y processing, AGC filtering, U-Net and Vision Transformer architectures, fault and horizon interpretation, and industrial visualization techniques developed during the ONGC internship.",
  },
  {
    id: "enterprise-copilots-research",
    slug: "enterprise-copilots-research",
    title: "Building Enterprise AI Copilots",
    date: "2024",
    readTime: "Exploration Topic",
    category: "Enterprise AI • RAG Systems",
    summary: "Research into offline RAG architectures, AST validation, enterprise knowledge retrieval, developer copilots, reasoning workflows, and secure AI systems inspired by the HPCC Copilot project.",
    content: "Research into offline RAG architectures, AST validation, enterprise knowledge retrieval, developer copilots, reasoning workflows, and secure AI systems inspired by the HPCC Copilot project.",
  },
];

// Backward-compatibility alias exports
export const HERO_DATA = {
  ...IDENTITY_DATA,
  bio: IDENTITY_DATA.mission,
  tagline: IDENTITY_DATA.subtitle,
  institution: IDENTITY_DATA.university,
  availability: IDENTITY_DATA.status,
};
export const TIMELINE_JOURNEY = TIMELINE_EVENTS;
export const ACHIEVEMENTS = ACHIEVEMENTS_DATA;
export const ENGINEERING_PHILOSOPHY = {
  overview: IDENTITY_DATA.mission,
  principles: [
    { number: "01", title: "Research Before Building", description: "Analyze underlying domain math before selecting frameworks." },
    { number: "02", title: "Build For Scale & Reliability", description: "Enforce strict static typing and modular boundaries." },
    { number: "03", title: "AI Must Solve Real Problems", description: "Fulfill explicit enterprise needs over trendy AI hype." },
    { number: "04", title: "Performance & Latency Matter", description: "Sub-100ms response times build user trust." },
    { number: "05", title: "Never Stop Learning", description: "Continuously explore cross-disciplinary fields." },
  ],
  whySoftware: "Software provides high-leverage engineering capabilities.",
  whyAi: "AI transforms complex mathematical and physical constraints into real-world automated leverage.",
};
export const FUTURE_VISION = {
  headline: "Strategic Engineering Vision 2026-2028+",
  statement: "Building high-impact industrial AI systems and software infrastructure.",
  goals: [
    "2026 — Graduate SRMIST B.Tech CSE (AI & ML) & Apple Developer Projects",
    "2027 — Enterprise AI Engineering & Open Source PyTorch Contributions",
    "2028 — Lead Industrial AI Copilot Architecture & Systems Engineering",
  ],
};
export const SKILL_GROUPS = [
  {
    category: "AI & Machine Learning" as const,
    description: "Deep learning models, computer vision pipelines, and RAG architectures.",
    skills: EVIDENCE_SKILLS.filter((s) => s.category === "AI & Machine Learning").map((s) => ({
      name: s.name,
      level: 95,
      tag: s.tag,
      highlight: true,
    })),
  },
  {
    category: "Backend & Systems Architecture" as const,
    description: "High-throughput asynchronous REST microservices and static analysis.",
    skills: EVIDENCE_SKILLS.filter((s) => s.category === "Backend & Systems Architecture").map((s) => ({
      name: s.name,
      level: 90,
      tag: s.tag,
      highlight: false,
    })),
  },
];
